#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    auto_complete = false
    colorscheme = "NeoSolarized"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
<<<<<<< HEAD
    autocomplete_method = 'deoplete'
#    autocomplete_method = 'lsp'
=======
    #autocomplete_method = 'deoplete'
>>>>>>> c920830f6bd108e167886cdb7d3557c51e304e33
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    vim_help_language = "cn"
    default_indent = 4
    bootstrap_before= "myspacevim#before"
    bootstrap_after= "myspacevim#after"
    disabled_plugins = ["auto_complete"]
    enable_neomake = false

# Enable autocomplete layer
#[[layers]]
#name = 'autocomplete'
#auto-completion-return-key-behavior = "smart"
#auto-completion-tab-key-behavior = "smart"

[[layers]]
name="colorscheme"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

<<<<<<< HEAD
[[layers]]
name = "lang#golsp"

#[[layers]]
#name = "lang#go"
=======
#[[layers]]
#name = "lang#go"

#[[layers]]
#name = "lang#rust"
>>>>>>> c920830f6bd108e167886cdb7d3557c51e304e33

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#java"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#typescript"

#[[layers]]
#name = "lang/vim"

[[layers]]
name = "fzf"

[[layers]]
name = "VersionControl"

[[layers]]
name = "tmux"

[[layers]]
name = 'autocomplete'
enable = false

[[custom_plugins]]
name = "terryma/vim-multiple-cursors"

[[custom_plugins]]
repo="https://github.com/lyokha/vim-xkbswitch"
merged=false

[[custom_plugins]]
name = "zivyangll/git-blame.vim"
merged=false

